global:
  scrape_interval: 30s

scrape_configs:
  - job_name: system
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'localhost:9100'
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus:9090'
